services:
  api:
    build: .
    container_name: golang_api
    environment:
      - GREENLIGHT_DB_DSN=${DATABASE_URL}
    ports:
      - "${PORT}:4000"
    depends_on:
      - db
  db:
    container_name: postgres_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      TZ: 'Asia/Ulaanbaatar'
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: